apiVersion: v1
kind: Service
metadata:
  name: map
spec:
  selector:
    app: map
  ports:
    - protocol: TCP
      port: 80
      targetPort: map-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: map
  labels:
    app: map
spec:
  replicas: 5
  selector:
    matchLabels:
      app: map
  template:
    metadata:
      labels:
        app: map
    spec:
      containers:
        - name: map
          image: fabdock/mapreduce-map
          ports:
            - name: map-port
              containerPort: 80