apiVersion: v1
kind: Service
metadata:
  name: reduce
spec:
  selector:
    app: reduce
  ports:
    - protocol: TCP
      port: 80
      targetPort: reduce-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reduce
  labels:
    app: reduce
spec:
  replicas: 5
  selector:
    matchLabels:
      app: reduce
  template:
    metadata:
      labels:
        app: reduce
    spec:
      containers:
        - name: reduce
          image: fabdock/mapreduce-reduce
          ports:
            - name: reduce-port
              containerPort: 80